[package]
name = "eye3rd"
version = "2.0.0"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive", "unicode"] }
zip = "2.2"
thiserror = "2"
log = "0.4"
simplelog = "0.12"
notify-rust = "4"
home = "0.5"
